# http://travis-ci.org/#!/jtriley/gpucrate
language: python
python:
    - 2.6
    - 2.7
install:
    - pip install -U setuptools
    - python setup.py install --quiet
script:
    - python setup.py test
